[package]
name = "photonix_derive"
version = "0.1.0"
authors = ["bsoptei <bsoptei@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = "0.4.26"
quote = "0.6.11"

[dependencies.syn]
version = "0.15.26"
features = ["full"]

[lib]
proc-macro = true

